### ISSUE TITLE
TEZAVA PRI UVOZU PODATKOV

### ISSUE THREAD

**Issue by jankoprogramko** [jankoprogramko/APPR-2019-20#1]
dodatne podrobnosti zapisana v komentarju za commit

**Comment by jaanos** [comment]
Kolikor vidim, gre za iste težave, kot si imel pri jankoprogramko/APPR-2018-19#2.

Mimogrede, spodobi se, da v issue napišeš, za kaj gre, oziroma vsaj, za kateri commit gre - skopiraš lahko njegovo šifro oziroma vsaj prvih 7 znakov (v tvojem primeru torej b0d55c2).
